name: Initialize Ubuntu-Latest Instance
on:
  workflow_dispatch:
jobs:
  init:
    name: Initialize Ubuntu-Latest Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Config sshd and credentials for root
        run: |
          sudo passwd -d root
          sudo cp -f ./ubuntu/sshd_config /etc/ssh/
          sudo systemctl restart sshd
      - name: install n2n
        run: |
          sudo dpkg -i ./ubuntu/n2n_3.0.0-1038_amd64.deb
      - name: launch n2n
        env:
          N2N_SERVER_ADDR: ${{ secrets.N2N_SERVER_ADDR }}
          N2N_SERVER_PORT: ${{ secrets.N2N_SERVER_PORT }}
          N2N_IP: ${{ secrets.N2N_IP }}
          N2N_COMMUNITY_NAME: ${{ secrets.N2N_COMMUNITY_NAME }}
          N2N_KEY: ${{ secrets.N2N_KEY }}
        run: |
          sudo /usr/sbin/edge -c $N2N_COMMUNITY_NAME -l $N2N_SERVER_ADDR:$N2N_SERVER_PORT -a $N2N_IP -I GitHub-Actions -k $N2N_KEY -A3
          sleep 6h