name: Windows
on:
  push:
  workflow_dispatch:
jobs:
  init:
    name: Initialize Windows-Latest Instance
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      # - name: Check user
      #   run: |
      #     whoami
      #     net user
      # - name: Modify password policy
      #   run: |
      #     secedit /configure /db gp.sdb /cfg .\p.inf /quiet
      # - name: New user
      #   run: |
      #     net user root Tgiu810@975 /add
      #     net localgroup Administrators root /add
      #     net user
      # - name: Activate Administrator
      #   run: |
      #     net user Administrator /active:yes
      #     net user
      # - name: 查看信任级别
      #   run: |
      #     runas /showtrustlevels
      # - name: trust level
      #   run: |
      #     runas /trustlevel:0x40000 whoami
      # - name: check arch
      #   run: |
      #     systeminfo
      - name: install tap
        run: |
          cd .\windows\amd64
          .\tapinstall.exe install OemVista.inf tap0901
      # - name: ipconfig
      #   run: |
      #     ipconfig
      # - name: install n2n
      #   run: |
      #     cp .\windows\edge.exe
      - name: Launch n2n
        env:
          N2N_SERVER_ADDR: ${{ secrets.N2N_SERVER_ADDR }}
          N2N_SERVER_PORT: ${{ secrets.N2N_SERVER_PORT }}
          N2N_COMMUNITY_NAME: ${{ secrets.N2N_COMMUNITY_NAME }}
          N2N_KEY: ${{ secrets.N2N_KEY }}
        run: |
          .\windows\edge.exe -c ${N2N_COMMUNITY_NAME} -l ${N2N_SERVER_ADDR}:${N2N_SERVER_PORT} -a 172.16.40.122 -I GitHub-Actions -k ${N2N_KEY} -A3
          sleep 3600
