name: MacOS
on:
  workflow_dispatch:
    inputs:
      IDENTIFIER:
        description: 'Specify an identifier:'
        required: true
        default: 'macos'
        type: string
      # USE_N2N:
      #   description: 'Use N2N edge to connect'
      #   required: true
      #   default: true
      #   type: boolean
      # N2N_IP:
      #   description: 'Specify the tap ip address for N2N edge'
      #   required: false
      #   default: '172.16.40.101'
      #   type: string
      USE_FRP:
        description: 'Use FRPC to connect'
        required: true
        default: true
        type: boolean
      FRP_SSH_PORT:
        description: 'Specify the remote SSH port for FRP'
        required: false
        default: '30022'
        type: string
      SSH_PUBKEY:
        description: 'Deploy personal SSH public key'
        required: false
        default: true
        type: boolean
      # SSH_HOST_KEY:
      #   description: 'Deploy static SSH host key'
      #   required: false
      #   default: true
      #   type: boolean
jobs:
  init:
    name: Initialize MacOS-Latest Instance
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Turn off the firewall
        run: |
          sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 0
      - name: Configure sshd service
        run: |
          sudo cp -f ./macos/ssh/sshd_config /etc/ssh/
          sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist
          sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist
      - name: Deploy personal SSH public key
        if: ${{ inputs.SSH_PUBKEY }}
        env:
          SSH_PUBKEY: ${{ secrets.SSH_PUBKEY }}
        run: |
          echo $SSH_PUBKEY > ./macos/ssh/authorized_keys
          cp -f ./macos/ssh/authorized_keys /Users/runner/.ssh/
          chown runner /Users/runner/.ssh/authorized_keys
          chmod 600 /Users/runner/.ssh/authorized_keys
          chmod 700 /Users/runner/.ssh
      - name: Install FRPC service
        if: ${{ inputs.USE_FRP }}
        run: |
          chmod +x ./macos/frp/frpc
      - name: Configure FRPC
        if: ${{ inputs.USE_FRP }}
        env:
          FRP_SERVER_ADDR: ${{ secrets.FRP_SERVER_ADDR }}
          FRP_SERVER_PORT: ${{ secrets.FRP_SERVER_PORT }}
          FRP_TOKEN: ${{ secrets.FRP_TOKEN }}
          FRP_SSH_PORT: ${{ inputs.FRP_SSH_PORT }}
          IDENTIFIER: ${{ inputs.IDENTIFIER }}
          FRP_CONF_FILE: ./macos/frp/frpc.ini
        run: |
          echo "[common]" > $FRP_CONF_FILE
          echo "server_addr = $FRP_SERVER_ADDR" >> $FRP_CONF_FILE
          echo "server_port = $FRP_SERVER_PORT" >> $FRP_CONF_FILE
          echo "authentication_method = token" >> $FRP_CONF_FILE
          echo "token = $FRP_TOKEN" >> $FRP_CONF_FILE
          echo "[ssh-$FRP_SSH_PORT-$IDENTIFIER]" >> $FRP_CONF_FILE
          echo "type = tcp" >> $FRP_CONF_FILE
          echo "local_ip = 127.0.0.1" >> $FRP_CONF_FILE
          echo "local_port = 22" >> $FRP_CONF_FILE
          echo "remote_port = $FRP_SSH_PORT" >> $FRP_CONF_FILE
      - name: Launch FRPC
        if: ${{ inputs.USE_FRP }}
        run: |
          sudo nohup ./macos/frp/frpc -c ./macos/frp/frpc.ini &
      - name: Maintaining
        run: |
          sleep 5m
