name: Windows
on:
  push:
  workflow_dispatch:
jobs:
  init:
    name: Initialize Windows-Latest Instance
    runs-on: windows-latest
    steps:
      # - name: Checkout source
      #   uses: actions/checkout@v2
      # - name: Check user
      #   run: |
      #     whoami
      #     net user
      # - name: Modify password policy
      #   run: |
      #     secedit /configure /db gp.sdb /cfg .\p.inf /quiet
      - name: New user
        run: |
          net user root TempPasswd114514 /add
          net localgroup Administrators root /add
          net user
      # - name: Activate Administrator
      #   run: |
      #     net user Administrator /active:yes
      #     net user
      # - name: 查看信任级别
      #   run: |
      #     runas /showtrustlevels
      # - name: trust level
      #   run: |
      #     runas /trustlevel:0x40000 whoami

